# Generated by Django 5.1.3 on 2024-12-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consented to study'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Agreed to privacy notice'),
        ),
    ]
